name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
          msystem: MINGW64
          update: true

    - name: Install dependencies
      run: pacman -Sq --noconfirm git pkgconf mingw-w64-x86_64-{cmake,qt5-static,toolchain}

    - name: Configure
      working-directory: ${{runner.workspace}}
      run: cmake -B build $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_STATIC=ON -DCMAKE_PREFIX_PATH=C:/tools/msys64/mingw64/qt5-static

    - name: Make
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .

    - uses: actions/upload-artifact@v3
      with:
        name: SchottenTotten_win_x64
        path: ${{runner.workspace}}\build\SchottenTotten.exe
