name: build

on:
  push:
    branches:
      - master
      - main
    tags:
      - "*"
  pull_request:

jobs:
  build-cmake:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc

        qt_version:
          - "6.4.3"

        include:
          - toolchain: linux-gcc
            os: ubuntu-20.04
            compiler: gcc
            executable: SchottenTotten
            name: SchottenTotten-linux-x64

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang
            executable: SchottenTotten.app\Contents\MacOS\SchottenTotten
            name: SchottenTotten-macos

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc
            executable: Release\SchottenTotten.exe
            name: SchottenTotten-windows-x64

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt_version }}

    - name: Setup (Linux)
      if: startsWith (matrix.os, 'ubuntu')
      run: sudo apt-get install libxkbcommon-dev

    - name: Setup VS tools (Windows)
      if: startsWith (matrix.os, 'windows')
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Make
      run: cmake --build build --config Release

    - name: Display structure of compiled files
      run: ls -R
      working-directory: build

    - uses: actions/upload-artifact@v3
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.executable }}

  publish-release:

    needs: build-cmake
    name: Publish Release
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v3
      name: Download builded executables
      with:
        path: artifacts
    - name: Zip executables
      run: |
        RELEASE_VERSION="${GITHUB_REF#refs/tags/v}""
        zip "SchottenTotten-${RELEASE_VERSION}-linux-x64" artifacts/SchottenTotten-linux64/SchottenTotten
        zip "SchottenTotten-${RELEASE_VERSION}-macos" artifacts/SchottenTotten-macos/SchottenTotten
        zip "SchottenTotten-${RELEASE_VERSION}-windows-x64" artifacts/SchottenTotten-win64/SchottenTotten.exe
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: artifacts
