name: build

on:
  push:
    branches:
      - master
      - main
    tags:
      - "*"
  pull_request:

jobs:
  build-cmake:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc

        qt_version:
          - "6.4.3"

        include:
          - toolchain: linux-gcc
            os: ubuntu-20.04
            compiler: gcc
            executable: SchottenTotten
            name: SchottenTotten-linux64.zip

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang
            executable: SchottenTotten
            name: SchottenTotten-macos.zip

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc
            executable: SchottenTotten.exe
            name: SchottenTotten-win64.zip

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt_version }}

    - name: Setup (Linux)
      if: startsWith (matrix.os, 'ubuntu')
      run: sudo apt-get install libxkbcommon-dev

    - name: Setup VS tools (Windows)
      if: startsWith (matrix.os, 'windows')
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Make
      run: cmake --build build --config Release

    - uses: actions/upload-artifact@v3
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        name: ${{ matrix.name }}
        path: build\Release\${{ matrix.executable }}

  publish-release:

    needs:
      - linux-gcc
      - macos-clang
      - windows-msvc
    name: Publish Release
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: artifacts
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: artifacts
