name: build

on:
  push:
    branches:
      - master
      - main
    tags:
      - "*"
  pull_request:

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc

        configuration:
          - Release

        include:
          - toolchain: linux-gcc
            os: ubuntu-20.04
            compiler: gcc
            qt_version: "6.4.3"

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang
            qt_version: "6.4.3"
            modules: ""

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc
            qt_version: "6.4.3"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt_version }}

    - name: Setup (Linux)
      if: startsWith (matrix.os, 'ubuntu')
      run: sudo apt-get install libxkbcommon-dev

    - name: Setup VS tools (Windows)
      if: startsWith (matrix.os, 'windows')
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Configure Release
      run: cmake -B build

    - name: Build with Release
      run: cmake --build build --config Release
