name: lint

on:
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: "Requirements"
      run: pip install pre-commit cpplint clang-format
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files
